### Create a new bin
POST http://localhost:3000/api/bin
### Test a request with a simple path
GET http://localhost:3000/endpoint/b4cbcb14d05b41beb6a87a496628c61b/testPath
### Test a request with no path
POST http://localhost:3000/endpoint/b4cbcb14d05b41beb6a87a496628c61b
### Test a request with a multi level path
PUT http://localhost:3000/endpoint/b4cbcb14d05b41beb6a87a496628c61b/level1/level2/level3
content-type: application/json

{
  "test": "test",
  "test2": "test2",
  "test3": "test3"
}

### Test a non existant endpoint
PUT http://localhost:3000/endpoint/doesntexist/level1/level2/level3

### Get all the logs from postgres log table for a given bin
GET http://localhost:3000/api/bin/1/logs
### Get the full JSON for a specific request in the MongoDB
GET http://localhost:3000/api/bin/1/log/65b85b554b4562d392250bb7
### Try to get the full JSON for a request that doesn't exist
GET http://localhost:3000/api/bin/1/log/65b7c5e2d239c39863b27861
### Try to get the full JSON for a request with an invalid id
GET http://localhost:3000/api/bin/1/log/tunamelt
### Delete a single log
DELETE http://localhost:3000/api/bin/1/log/2
### Delete all logs for an endpoint
DELETE http://localhost:3000/api/bin/1/log